### PR TITLE
Register invoice

### LINKED ISSUE #24: Implement invoice view of 'cart'
The invoice currently has a fixed text, but this should change. It should be based on the state.

### LINKED ISSUE #27: Adjust T-shirt price based on package selected

### LINKED ISSUE #62: T-shirt size dropdown is broken

### PR DESCRIPTION
**Pull request by angryzor**
Fixes #24 , fixes #27 and fixes #62

### CODE REVIEW

File: src/components/funnels/funnels/register/steps/ticket/level.tsx [hunk 1]
```diff
@@ -33,26 +34,27 @@ const AddonsContainer = styled.section`
...
 const TicketLevel = (_: ReadonlyRouteComponentProps) => {
-	const { register, control, handleSubmit } = useFunnelForm<TicketLevelModel>(ChangeTicketLevel, SubmitTicketLevel)
-	const { ticketLevels, tshirtSizes, registrationExpirationDate } = useSiteMetadata()
+	const ticketType = useAppSelector(getTicketType())!
+	const { register, control, handleSubmit, watch } = useFunnelForm<TicketLevelModel>(ChangeTicketLevel, SubmitTicketLevel)
+	const level = watch('level', 'standard')
 
 	const { sizes, sizesByValue } = useMemo(() => {
-		const sizes = tshirtSizes.map(size => ({ value: size, label: size }))
+		const sizes = config.tshirtSizes.map(size => ({ value: size, label: size }))
```
Comment (ErikMelton) [inline src/components/funnels/funnels/register/steps/ticket/level.tsx:42]: Probably OK, but might rename inner `sizes` to `shirtSizes` or something similar to prevent the scope clash

**Review by ErikMelton — APPROVED** [review]
